dashboard/urls.py
from django.conf.urls import url
from . import views


app_name = 'dashboard'

urlpatterns = [
    url(r'^tables', views.tables, name='tables'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),
    url(r'^word_search/make_anki', views.make_anki_text, name='make_anki_text'),
    url(r'^word_search/', views.word_search, name='word_search'),
    url(r'^textfile_word_search/', views.textfile_word_search, name='textfile_word_search'),
    url(r'^$', views.index, name="dashboard"),
    url(r'^exam/(?P<exam_id>[0-9]+)/(?P<turn_in>[-\w]+)/$', views.exam, name="exam"),
    url(r'^exam/(?P<exam_id>[0-9]+)/', views.exam, name="exam"),
    url(r'^class/(?P<school_class_id>[0-9]+)/', views.dashboard, name="school_class_dashboard"),
    url(r'^turn_in_exam/(?P<exam_paper_id>[0-9]+)/$', views.turn_in_exam, name="turn_in_exam"),
    # url(r'^exam/(?P<exam_id>[0-9]+)/save_answer/$', views.save_answer, name="save_answer"),
    url(r'^save_answer/$', views.save_answer, name="save_answer"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^change_user_image/$', views.change_user_image, name='change_user_image'),
    url(r'create_post/(?P<school_class_id>[0-9]+)/$', views.PostCreate.as_view(), name='create_post'),
    # url(r'^video/(?P<pk>[0-9]+)/$',
    #     views.VideoDetailView.as_view(), name="video"),
    url(r'^video/(?P<video_id>[0-9]+)/$',
        views.video_view, name="video"),
    url(r'^mark_video_watched/(?P<step_id>[0-9]+)/(?P<video_id>[0-9]+)/$',
        views.toggle_video_watched, name="toggle_video_watched")
]

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load app_filters %}

{% block content %}

<div class="content">
  <div class="container-fluid">

    <h3 id="course_title" class="title text-center">{{school_class.name}}</h3>
    <span class="percentage_class">{{school_class_user_table.get_percentage_complete}}</span>%
    <!-- Progress Bar -->
    <div class="progress progress-striped ">
      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{school_class.get_percentage_completed}}" aria-valuemin="0" aria-valuemax="100" style="width:{{school_class_user_table.get_percentage_complete}}%">
        <span class="sr-only">{{school_class_user_table.get_percentage_complete}}% Complete</span>
      </div>
    </div>

    <div class="tab-content">

      <div class="card">
          <div class="card-header">
              <h4 class="card-title">{{school_class.name}} -
                  <small class="category">Lessons</small>
              </h4>
          </div>
          <div class="card-content">
              <div class="row">
                  <div class="col-md-4">


                      <!-- Navigation -->
                      <ul class="nav nav-pills nav-pills-icons nav-pills-rose nav-stacked" role="tablist">

                          {% for step in school_class.get_published_steps %}
                              <li class="{%   if forloop.first %}active{% endif %}">
                                  <a href="#step{{step.id}}" role="tab" data-toggle="tab">
                                      <i class="material-icons">dashboard</i> Lesson {{ forloop.counter }}) {{step.name}}
                                  </a>
                              </li>
                          {% endfor %}
                      </ul>
                      <!-- End Navigation  -->


                  </div>
                  <div class="col-md-8">
                      <div class="tab-content">

                          <!-- Step Content -->
                          {% for step in school_class.get_published_steps %}
                          <div class="tab-pane {% if forloop.first %}active{% endif %}" id="step{{step.id}}">
                              
                              {{step.description}}<br>



                              <!-- Videoes And Video Modal -->
                              {% for video in step.videos.all %}

                              <label checked onchange="mark_video_watched({{video.id}}, {{step.id}})" id="video_input{{video.id}}" class="videoWatchedCheckmark checkbox">
                                  <input name="optionsCheckboxes" {% if video.id in completed_videos_ids %} checked {% endif %} type="checkbox">
                                  <span class="checkbox-material"><span class="check"></span></span>
                              </label><i class="fa fa-video-camera fa-fw"></i>{{video.name}}
                              {% if video.youtube_link or video.youtube_link %}
                              <span data-toggle="tooltip" data-placement="top" title="Switch to Youku Player!" id="videoIcon{{video.id}}"  onclick="switchVideoPlayer({{video.id}})" class="cursor fa-stack fa-pull-right fa-border fa-1x fa-lg">
                                <i  class="fa fa-youtube  fa-stack-1x"></i>
                                <i id="redX" class="fa fa-ban fa-stack-2x text-danger"></i>
                              </span>
                              <br>
                              {% endif %}

                              <!-- Show Video Player Embed Link -->
                              {% if video.youtube_link or video.youtube_link %}


                                {% if country != "United States" %}

                                  <span data-youku-id="{{video.get_youku_id}}" data-youtube-id="{{video.get_youtube_id}}" data-video-player="youku" id="videoPlayer{{video.id}}">{{ video.get_youku_embed_link | safe}}</span>
                                {% else %}
                                  
                                  <span data-youku-id="{{video.get_youku_id}}" data-youtube-id="{{video.get_youtube_id}}" data-video-player="youtube" id="videoPlayer{{video.id}}">{{ video.get_youtube_embed_link | safe}}</span>
                                {% endif %}


                              {% else %}                        
                                <br>
                                <a class="video_modal_link"  data-toggle="modal" data-target="#video{{video.id}}" href="" onclick="loadVideo({{video.id}})">
                                  <p>

                                      <i class="fa fa-video-camera fa-fw"></i>
                                      {{video.name}}
                                  </p>
                                </a><br>
                              {% endif %}

                                  <!-- Video Modal -->    
                                  <div class="modal fade myModal" id="video{{video.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                      <div class="modal-dialog">
                                          <div class="modal-content">
                                              <div class="modal-header">
                                                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                  <h4 class="modal-title" id="myModalLabel">{{video.name}}</h4>
                                              </div>

                                              <div class="modal-body">

                                                  
                                              </div>

                                              <div class="modal-footer">
                                                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <!-- End Video Modal -->


                              
                              {% endfor %}
                              <!-- End Videoes And Video Modal -->

                              <!-- Exam -->
                              <!-- This is EXTREMELY MESSY CODE! CLEAN IT UP! -->
                              {% if step.exam %}
                                <a href="{{ step.exam.get_absolute_url }}">{{step.exam.name}}</a>



                                <!-- Exam -->
                                {% for exam_paper in exam_paper_list %}
                                  {% if exam_paper.id == step.id %}

                                    {% if exam_paper.exam_paper.exam.get_questions %}


                                    <h2>
                                     {{exam.name}}
                                     {% if exam_paper.exam_paper.is_turned_in %}
                                     Score: {{ exam_paper.exam_paper.get_score  }}
                                     {% else %}
                                     <br>
                                     <a href="{% url 'dashboard:exam' turn_in='true' exam_id=exam_paper.exam_paper.exam.id  %}">
                                       <button class="btn btn-danger btn-fill btn-just-icon">Turn In Exam</button>
                                     </a>
                                     {% endif %}
                                    </h2>

                                     <!-- a hidden input to tell saveAnswer function in main.js
                                          what the url to send answers to -->
                                     <span id="save_answer_span" >
                                       <input type="hidden" value="save_answer/" id="save_answer_url" name="answer_url">
                                       {% csrf_token %}
                                       {% for question in exam_paper.exam_paper.exam.get_questions %}
                                        <div id="question{{question.id}}" class="panel panel-default">
                                            <div class="panel-heading">
                                            {{forloop.counter}}) {{question.question}}

                                            <!-- Selected Answer is showed here -->
                                            <!-- I added comment tags to get rid of white spaces between django tags. stupid, but eh. -->
                                            <span id="saved_answer{{question.id}}" class="label label-success"><!-- 
                                             -->{% for answer in question.get_answers %}<!-- 
                                               -->{% for selection in  exam_paper.exam_paper.selections.all %}<!-- 
                                               -->{% if answer == selection.answer %}<!-- 
                                               -->{{ answer.answer }}<!-- 
                                               -->{% endif %}<!-- 
                                               -->{% endfor %}<!-- 
                                             -->{% endfor %}<!-- 
                                             --></span>

                                            <!-- Questio Image if it exists -->
                                            {% if question.image %}
                                            <br><a href="{{ question.image.image.url }}"><img class="question_image" src="{{ question.image.image.url }}"></a>
                                            {% endif %}


                                            </div>
                                            <!-- On click the answer will be saved using saveAnswer function
                                                 of main.js. -->
                                            <div class="answer_body panel-body">

                                                {% for answer in question.get_answers %}
                                                   <span class="cursor an_answer my_pointer" onclick="saveAnswer({{answer.id}}, {{exam_paper.exam_paper.id}}, {{question.id}})" id="answer{{answer.id}}">
                                                   {{forloop.counter | to_char}}) - {{answer.answer}}
                                                   </span></br></br>
                                                {% endfor %}
                                            </div>
                                        </div>
                                      </span>
                                      {% endfor %}
                                    {% endif %}
                                    <!-- End if exam_paper.exam_paper.exam.get_questions -->

                                  {% endif %}
                                {% endfor %}



                              {% endif %}
                              <!-- End if step.exam -->



                          </div>
                          {% endfor %}
                          <!-- End Step Content -->
                      </div>
                  </div>
              </div>
          </div>
      </div>

    </div>
  </div> 
</div>

{% endblock %}

dashboard/templates/dashboard/exam.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load app_filters %}

{% block content %}

<div class="content">
    <div class="container-fluid">

        <!-- First Row  -->
        <div class="col-md-12">
               <h2>
               {{exam.name}}
               {% if exam_paper.is_turned_in %}
               Score: {{ exam_paper.get_score  }}
               {% else %}
               <br>
               <a href="{% url 'dashboard:exam' turn_in='true' exam_id=exam.id  %}">
                 <button class="btn btn-danger btn-fill btn-just-icon">Turn In Exam</button>
               </a>
               {% endif %}
               </h2>   
                  <h5>Please answer the questions below.</h5>
                  


                   {% if exam.get_questions %}
                     <!-- a hidden input to tell saveAnswer function in main.js
                          what the url to send answers to -->
                     <span id="save_answer_span" >
                       <input type="hidden" value="save_answer/" id="save_answer_url" name="answer_url">
                       {% csrf_token %}
                       {% for question in exam.get_questions %}
                        <div id="question{{question.id}}" class="panel panel-default">
                            <div class="panel-heading">
                            {{forloop.counter}}) {{question.question}}

                            <!-- Selected Answer is showed here -->
                            <!-- I added comment tags to get rid of white spaces between django tags. stupid, but eh. -->
                            <span id="saved_answer{{question.id}}" class="label label-success"><!-- 
                             -->{% for answer in question.get_answers %}<!-- 
                               -->{% for selection in exam_paper.selections.all %}<!-- 
                               -->{% if answer == selection.answer %}<!-- 
                               -->{{ answer.answer }}<!-- 
                               -->{% endif %}<!-- 
                               -->{% endfor %}<!-- 
                             -->{% endfor %}<!-- 
                             --></span>

                            <!-- Questio Image if it exists -->
                            {% if question.image %}
                            <br><a href="{{ question.image.image.url }}"><img class="question_image" src="{{ question.image.image.url }}"></a>
                            {% endif %}


                            </div>
                            <!-- On click the answer will be saved using saveAnswer function
                                 of main.js. -->
                            <div class="answer_body panel-body">

                                {% for answer in question.get_answers %}
                                   <span class="cursor an_answer my_pointer" onclick="saveAnswer({{answer.id}}, {{exam_paper.id}}, {{question.id}})" id="answer{{answer.id}}">
                                   {{forloop.counter | to_char}}) - {{answer.answer}}
                                   </span></br></br>
                                {% endfor %}
                            </div>
                        </div>
                      </span>
                      {% endfor %}
                    {% endif %}
                 
              </div>
        <!-- End First Row -->

        <!-- Second Row -->
<!--         <div class="row">
            <div class="card">
                <div class="card-header" data-background-color="orange">
                    <h4 class="card-title">Question Number 1</h4>
                    <p class="category">A Book class is to be written, containing the following data fields: age , which will be initialized to 0 when an Book is constructed. nextAvailableID , which will be initialized to 0 outside the constructor and in- cremented each time a Book is constructed. idNum , which will be initialized to the current value of nextAvailableID when a Book is constructed. position , which will be initialized to the shelf location in a bookstore where the Book is placed when it is constructed. direction , which will be initialized to the direction the Book is facing when placed in the shelf. Which variable in the Book class should be static? (C) idNum (D) position (E) direction </p>
                </div>
                <div class="card-content">


                    <div class="answer_body panel-body">
                                                    
                       <span class="an_answer my_pointer" onclick="saveAnswer(109, 32, 29)" id="answer109">
                       a) - idNum
                       </span><br><br>

                       <span class="an_answer my_pointer" onclick="saveAnswer(110, 32, 29)" id="answer110">
                       b) - position
                       </span><br><br>

                       <span class="an_answer my_pointer" onclick="saveAnswer(107, 32, 29)" id="answer107">
                       c) - nextAvailableID
                       </span><br><br>

                       <span class="an_answer my_pointer" onclick="saveAnswer(108, 32, 29)" id="answer108">
                       d) - age
                       </span><br><br>

                       <span class="an_answer my_pointer" onclick="saveAnswer(111, 32, 29)" id="answer111">
                       e) - direction
                       </span><br><br>
                                                    
                    </div>


                </div>
            </div>
        </div> -->
        <!-- End Second Row -->


    </div>
</div>

{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load app_filters %}

{% block content %}

<div class="content">
  <div class="container-fluid">
    <h3>Library</h3>
    <br>

    {% for row in course_rows %}
    <div class="row">


        <!-- Columns -->
        {% for course in row %}
        <div class="col-md-4">
            <div class="card card-product">
                <div class="card-image" data-header-animation="true">
                    <a href="#pablo">
                        <img class="img" src="{% static 'dashboard/img/student.jpeg' %}">
                    </a>
                </div>
                <div class="card-content">
                    <div class="card-actions">
                        <button type="button" class="btn btn-danger btn-simple fix-broken-card">
                            <i class="material-icons">build</i> Fix Header!
                        </button>
                        <a href="{{course.get_absolute_url}}"><button type="button" class="btn btn-default btn-simple" rel="tooltip" data-placement="bottom" title="View">
                                                    <i class="material-icons">art_track</i>
                                                </button></a>
                        <button type="button" class="btn btn-success btn-simple" rel="tooltip" data-placement="bottom" title="Edit">
                            <i class="material-icons">edit</i>
                        </button>
                        <button type="button" class="btn btn-danger btn-simple" rel="tooltip" data-placement="bottom" title="Remove">
                            <i class="material-icons">close</i>
                        </button>
                    </div>
                    <h4 class="card-title">
                        <a href="{{course.get_absolute_url}}">{{course.name}}</a>
                    </h4>
                    <div class="card-description">
                        {% if course.description %}
                          {{course.description | truncatechars:180 }}
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer">
                    <div class="price">
                        <h4>$899</h4>
                    </div>
                    <div class="stats pull-right">
                        <p class="category"><i class="material-icons">place</i> Chengdu, China</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}


    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

dashboard/templates/dashboard/login.html
{% extends 'dashboard/login_register_base.html' %}
{% load widget_tweaks %}
{% load static %}

<!-- Image must be 2880 x 1924 -->
{% block data_image %} data-image="{% static 'dashboard/img/register.jpeg' %}" {% endblock %}

{% block login_nav_class %}active{% endblock %}

{% block login_register_form %}
<form action="{% url 'dashboard:login' %}" method="post">
    {% csrf_token %}
    <div class="card card-login card-hidden">
        <div class="card-header text-center" data-background-color="rose">
            <h4 class="card-title">Login</h4>
            
        </div>
        
        <div class="card-content">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">face</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Username</label>
                    {{ form.username|attr:"class:form-control"  }}
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">lock_outline</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Password</label>
                    {{ form.password|attr:"class:form-control"  }}
                </div>
            </div>
        </div>
        <div class="footer text-center">
            <button type="submit" class="btn btn-rose btn-round">Login</button>
        </div>
    </div>
</form>
{% endblock %}

dashboard/templates/dashboard/login_register_base.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block body %}
<body>
    <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'frontpage:index' %}">JXFLS International High School</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block register_nav_class %}{% endblock %}">
                        <a href="{% url 'dashboard:register' %}">
                            <i class="material-icons">person_add</i> Register
                        </a>
                    </li>
                    <li class="{% block login_nav_class %}{% endblock %}">
                        <a href="{% url 'dashboard:login' %}">
                            <i class="material-icons">fingerprint</i> Login
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="wrapper wrapper-full-page">
        <!-- Image must be 2880 x 1924 -->
        <div class="full-page login-page" filter-color="black" {% block image %} data-image="{% static 'dashboard/img/lock.jpeg' %}" {% endblock %} >
            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">

                            {% block login_register_form %}
                            <form action="{% url 'dashboard:register' %}" method="post">
                                {% csrf_token %}
                                <div class="card card-login card-hidden">
                                    <div class="card-header text-center" data-background-color="rose">
                                        <h4 class="card-title">Login</h4>
                                        
                                    </div>
                                    
                                    <div class="card-content">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">face</i>
                                            </span>
                                            <div class="form-group label-floating">
                                                <label class="control-label">Username</label>
                                                {{ form.username|attr:"class:form-control"  }}
                                            </div>
                                        </div>
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock_outline</i>
                                            </span>
                                            <div class="form-group label-floating">
                                                <label class="control-label">Password</label>
                                                {{ form.password|attr:"class:form-control"  }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="footer text-center">
                                        <button type="submit" class="btn btn-rose btn-round">Login</button>
                                    </div>
                                </div>
                            </form>
                            {% endblock %}



                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="{% url 'frontpage:index' %}">
                                    JXFLS IHS
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        Jiaxiang Foreign Languages School Attached to Chengdu No.7 Middle School International High School
                    </p>
                </div>
            </footer>
        </div>
    </div>
</body>
{% endblock %}

dashboard/templates/dashboard/register.html
{% extends 'dashboard/login_register_base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block register_nav_class %} active {% endblock %}

{% block login_register_form %}
<form action="{% url 'dashboard:register' %}" method="post">
    {% csrf_token %}
    <div class="card card-login card-hidden">
        <div class="card-header text-center" data-background-color="rose">
            <h4 class="card-title">Register</h4>
            
        </div>
        
        <div class="card-content">
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">face</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Username</label>
                    {{ form.username|attr:"class:form-control"  }}
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">email</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Email address</label>
                    {{ form.email|attr:"class:form-control"  }}
                </div>
            </div>
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="material-icons">lock_outline</i>
                </span>
                <div class="form-group label-floating">
                    <label class="control-label">Password</label>
                    {{ form.password|attr:"class:form-control"  }}
                </div>
            </div>
        </div>
        <div class="footer text-center">
            <button type="submit" class="btn btn-rose btn-round">Register</button>
        </div>
    </div>
</form>
{% endblock %}

dashboard/templates/dashboard/video_detail.html
<video id="cute" width="320" height="240" controls>
	{% if video.file %}
	<source src="{{video.file.url}}" type="video/mp4">
	<source src="{{video.file.url}}" type="video/webm">
	Your browser does not support the video tag.
	{% endif %}
</video>
<br>